export const columnsMaison = [
  { field: 'id', title: 'ID', editable: false, resizable: false },
  { field: 'nom', title: 'Nom', filter: 'text', editable: false, resizable: false },
  // { field: 'piece', title: 'Pièces', editable: false, resizable: false },
  { field: 'caracteristique', title: 'Caractéristiques', editable: false, resizable: false },
//   { field: 'images', title: 'Images', editable: false, resizable: false },
//   { field: 'measure', title: 'Mesure', editable: false, resizable: false },
  { field: 'agentId', title: 'Agent', editable: false, resizable: false },
  { field: 'cityId', title: 'Ville (ID)', editable: false, resizable: false },
  { field: 'communeId', title: 'Commune (ID)', editable: false, resizable: false },
//   { field: 'propertyId', title: 'Propriété', editable: false, resizable: false },
  { field: 'statusPropertyId', title: 'Statut', editable: false, resizable: false },
//   { field: 'isDisponible', title: 'Disponible', editable: false, resizable: false },
  { field: 'superficie', title: 'Superficie', editable: false, resizable: false },
  { field: 'prix', title: 'Prix', filter: 'text', editable: false, resizable: false },
  { field: 'partPayed', title: 'Tranche', filter: 'text', editable: false, resizable: false },
  { field: 'countryId', title: 'Pays (ID)', editable: false, resizable: false },
//   { field: 'codePostal', title: 'Code Postal', editable: false, resizable: false },
];
